### ISSUE TITLE
Todo list for DEV -> MASTER

### ISSUE THREAD

**Issue by zeroFruit** [swsnu/swpp2019-team16#98]
@dkim94 @mss8087 @Teapot404 

### Subject of this issue

In the dev branch, there are lots of bad quality codes. Besides, some codes are absent for test code. We need to fix them.

## TODO LIST FOR MERGING MASTER

- [x] check `carpool_request` component test cases with code qualities (if there's any `TODO:` comment)
- [x] check `group` component test cases with code qualities (if there's any `TODO:` comment)
- [x] check `grpc_gateway` test cases with code qualities (if there's any `TODO:` comment)
- [x] check `api_gateway` test cases with code qualities (if there's any `TODO:` comment)
- [x] check `WaitingContainer` test cases with code qualities (if there's any `TODO:` comment)
- [x] implement user register / login / logout feature at `api_gateway`
